### ISSUE TITLE
Google Cloud Functions Gen 2

### ISSUE THREAD

**Issue by janpio** [prisma/ecosystem-tests#3556] opened 2023-05-27 08:25 UTC
https://cloud.google.com/functions/docs/concepts/version-comparison
https://cloud.google.com/functions/docs/console-quickstart

**Comment by Jolg42** [comment] 2023-05-30 12:59
Duplicate of https://github.com/prisma/ecosystem-tests/issues/3377 😉

**Closed as not planned by Jolg42** 2023-05-30 12:59 UTC
