### ISSUE TITLE
Serialize check-for-update

### ISSUE THREAD

**Issue by divyenduz** [prisma/ecosystem-tests#1113] opened 2020-11-26 16:21 UTC
`check-for-update` job is slow but scheduled. This means that at times multiple of these are running. We can think of serializing them using something like https://github.com/softprops/turnstyle

This issue tracks describing and implementing this.

**Comment by janpio** [comment] 2021-07-11 15:21
Duplicate of https://github.com/prisma/e2e-tests/issues/696

**Closed as completed by janpio** 2021-07-11 15:21 UTC
Labels: kind/improvement, topic: ci
