### ISSUE TITLE
Job that confirms test.yaml includes all projects/folders

### ISSUE THREAD

**Issue by janpio** [prisma/ecosystem-tests#734] opened 2020-08-26 13:53 UTC
Right now it is a lot of work to confirm that all folders and projects are actually executed in the test.yaml workflow. This could be solved by a small script that is executed as the first step of the workflow that gets all the folders, and checks if they are mentioned in the matrixes of the test.yaml workflow definition. If not, it fails.

**Comment by divyenduz** [comment] 2020-10-12 12:32
This sounds like a duplicate of https://github.com/prisma/e2e-tests/issues/254

**Closed as completed by divyenduz** 2020-10-12 12:32 UTC
Labels: kind/improvement
